import type {Metadata} from "next";
import {IBM_Plex_Mono, Libre_Baskerville, Lora} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/toggle-theme";

const libreBaskerville = Libre_Baskerville({
    weight: ["400", "700"],
    subsets: ["latin"],
    variable: "--font-sans",
    display: "swap",
});

const lora = Lora({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-serif",
    display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-mono",
    display: "swap",
});

export const metadata: Metadata = {
    title: "MindCanvas - Blogs For Everyone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`
            ${libreBaskerville.variable}
            ${lora.variable}
            ${ibmPlexMono.variable} 
          antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {/* Floating Mode Toggle */}
            <div className="fixed top-4 right-4 z-50 print:hidden">
                <ModeToggle/>
            </div>

            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}