import type {Metadata} from "next";
import {Cormorant_Garamond, Fira_Mono, Poppins} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/toggle-theme";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: "400",
});

const cormorant_Garamond = Cormorant_Garamond({
    subsets: ["latin"],
    variable: "--font-cormorant-garamond",
    display: "swap",
    weight: "400",
});

const fira_Mono = Fira_Mono({
    subsets: ["latin"],
    weight: "400",
    display: "swap",
    variable: "--font-fira-mono",
});

export const metadata: Metadata = {
    title: "MindCanvas - Blogs For Everyone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${poppins.variable} ${cormorant_Garamond.variable} ${fira_Mono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {/* Floating Mode Toggle */}
            <div className="fixed top-4 right-4 z-50 print:hidden">
                <ModeToggle/>
            </div>

            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}