import type {Metadata} from "next";
import {Cormorant_Garamond, Poppins} from "next/font/google";
import "./globals.css";
import React from "react";

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const cormorantGaramond = Cormorant_Garamond({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-cormorant",
    weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
    title: "MindCanvas - Blogs For Everyone",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${cormorantGaramond.variable} ${poppins.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}

